### ISSUE TITLE
How to use join table in pgroonga_command select ?

### ISSUE THREAD

**Issue by lwq057** [pgroonga/pgroonga#254] opened 2022-11-16 02:56 UTC
Because some fields need to be updated frequently, you want to distinguish multiple tables.

What is the solution to federate other tables in search?

SQL like join tables

**Comment by komainu8** [comment] 2022-11-16 05:39
What kind of problem is happening when you use normal SQL instead of `pgroonga_command()`?

Currently, `pgroonga_commnd()` can not JOIN like SQL.
Because current PGroonga index interface can not express Groonga's schema that refer to other tables.

**Comment by lwq057** [comment] 2022-11-16 07:42
Or what other solutions?

The content of the index needs to be sorted by hits and publishing time. I added the hits of articles to the index, but it is particularly slow to update the hits each time.

**Comment by lwq057** [comment] 2022-11-16 07:48
Index：
`CREATE INDEX pgroonga_data_index ON public.data USING pgroonga ("ID", title, content, tag, author, "time", comment, hot, "like", "state");`

UPDATE：
` UPDATE "data" SET "hot" = "hot" + 1 WHERE "ID" IN (1002456,988763,589245,6846254,4732758,4624135);`

**Comment by komainu8** [comment] 2022-11-17 05:03
Could you provide reproduce procedure and data?

**Comment by lwq057** [comment] 2022-11-17 07:40
This is a query, Very slow after updating ：
`
            SELECT pgroonga_command('select',
                ARRAY[
                    'table', pgroonga.table_name('pgroonga_data_index'),
                    'match_columns', 'title * 4 || content || tag * 2 || author * 3',
                    'query', pgroonga_query_escape('keyword'),
                    'filter', 'state==1',
                    'output_columns','ID',
                    'sort_keys','-time',
                    'limit','20',
                    'offset','20',
                    'n_workers','-1'
                ]
            );
`

This is the database table structure：
`
CREATE TABLE public.data (
    "ID" integer NOT NULL,
    title character varying(180) NOT NULL,
    content text NOT NULL,
    tag character varying(150) NOT NULL,
    author character varying(50) DEFAULT ''::character varying,
    cover text,
    "time" timestamp(0) without time zone,
    state smallint DEFAULT 0,
    comment integer DEFAULT 0,
    hot integer DEFAULT 1,
    "like" integer DEFAULT 0,
    dislike integer DEFAULT 0,
    ip character varying(50),
    note text
);
`

Index：
`CREATE INDEX pgroonga_data_index ON public.data USING pgroonga ("ID", title, content, tag, author, "time", comment, hot, "like", "state");`

UPDATE，Everything is very slow after the update：
`UPDATE "data" SET "hot" = "hot" + 1 WHERE "ID" IN (1002456,988763,589245,6846254,4732758,4624135);`


data，It is the data of some articles, but the data volume is relatively large。

**Comment by lwq057** [comment] 2022-11-17 07:58
The current problem should be that updating several fields in the index will affect the index of the whole row。

If the frequently updated fields can be indexed separately, It can be used to sort the results when querying。

**Comment by kou** [comment] 2022-11-22 08:36
Why do you need to include `hot` to your PGroonga index? It seems that your query doesn't use it.

**Comment by kou** [comment] 2022-11-22 08:44
Why do you want to use `pgroonga_command('select', ...)` not `SELECT ... FROM ... WHERE` in this use case?

**Comment by lwq057** [comment] 2022-11-22 09:53
"Hot" will be used in query sorting

`'sort_keys','-hot',`

**Comment by kou** [comment] 2022-11-22 20:07
OK. Then why do you want to use `SELECT pgroonga_command('select', ..., 'sort_keys', '-hot', ...)` instead of `SELECT ... FROM ... ORDER BY hot DESC`?

**Comment by lwq057** [comment] 2022-11-23 06:30
It will be much slower to use ORDER BY hot DESC

**Comment by kou** [comment] 2022-11-23 07:25
Could you show `EXPLAIN ANALYZE VERBOSE SELECT ... ORDER BY hot DESC`?

**Comment by lwq057** [comment] 2022-11-23 08:48
```
EXPLAIN ANALYZE VERBOSE
SELECT pgroonga_command('select',
		ARRAY[
				'table', pgroonga.table_name('pgroonga_data_index'),
				'match_columns', 'title * 4 || content || tag * 2 || author * 3',
				'query', pgroonga_query_escape('music'),
				'output_columns','ID',
				'sort_keys','-hot',
				'limit','20',
				'offset','0',
				'n_workers','-1'
		]
);

EXPLAIN ANALYZE VERBOSE
SELECT "ID" FROM "data"
WHERE ARRAY["title", "content","tag","author"] &@
       ('music',
        ARRAY[4,1,2,3],
        'pgroonga_data_index')::pgroonga_full_text_search_condition
ORDER BY "hot" DESC
LIMIT 20
```

```
Result  (cost=0.00..0.01 rows=1 width=32) (actual time=2.864..2.864 rows=1 loops=1)
  Output: pgroonga_command('select'::text, ARRAY['table'::text, pgroonga.table_name('pgroonga_data_index'::cstring), 'match_columns'::text, 'title * 4 || content || tag * 2 || author * 3'::text, 'query'::text, 'music'::text, 'output_columns'::text, 'ID'::text, 'sort_keys'::text, '-hot'::text, 'limit'::text, '20'::text, 'offset'::text, '0'::text, 'n_workers'::text, '-1'::text])
Planning Time: 0.024 ms
Execution Time: 2.873 ms
```

```
Limit  (cost=451706.57..451708.90 rows=20 width=8) (actual time=1508669.401..1508894.673 rows=20 loops=1)
  Output: "ID", hot
  ->  Gather Merge  (cost=451706.57..451810.41 rows=890 width=8) (actual time=1508669.399..1508894.670 rows=20 loops=1)
        Output: "ID", hot
        Workers Planned: 2
        Workers Launched: 2
        ->  Sort  (cost=450706.54..450707.65 rows=445 width=8) (actual time=1508589.770..1508589.771 rows=16 loops=3)
              Output: "ID", hot
              Sort Key: data.hot DESC
              Sort Method: top-N heapsort  Memory: 26kB
              Worker 0:  actual time=1508545.103..1508545.105 rows=20 loops=1
                Sort Method: top-N heapsort  Memory: 26kB
              Worker 1:  actual time=1508555.641..1508555.643 rows=20 loops=1
                Sort Method: top-N heapsort  Memory: 26kB
              ->  Parallel Seq Scan on public.data  (cost=0.00..450694.70 rows=445 width=8) (actual time=33809.946..1508589.466 rows=68 loops=3)
                    Output: "ID", hot
                    Filter: ((ARRAY[data.title, (data.content)::character varying, data.tag, data.author])::text[] &@ '(music,"{4,1,2,3}",pgroonga_data_index)'::pgroonga_full_text_search_condition)
                    Rows Removed by Filter: 355878
                    Worker 0:  actual time=4112.136..1508544.756 rows=76 loops=1
                    Worker 1:  actual time=43554.248..1508555.304 rows=64 loops=1
Planning Time: 0.121 ms
Execution Time: 1508894.728 ms
```

**Comment by kou** [comment] 2022-11-23 19:28
> ```text
>               ->  Parallel Seq Scan on public.data  (cost=0.00..450694.70 rows=445 width=8) (actual time=33809.946..1508589.466 rows=68 loops=3)
> ```

PGroonga index isn't used.

You can't use `pgroonga_data_index` for `ARRAY["title", "content","tag","author"] &@` because the target column is different.

Could you try the following?

```sql
CREATE INDEX pgroonga_data_index2
  ON public.data
 USING pgroonga ((ARRAY[title::text, content, tag::text, author::text]));
 
EXPLAIN ANALYZE VERBOSE
SELECT "ID" FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('music',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition
ORDER BY hot DESC;
```

**Comment by kou** [comment] 2022-11-23 19:59
Why is it important for your use case?
Performance? If so, could you provide `EXPLAIN ANALYZE VERBOSE SELECT COUNT(*) ...` and `EXPLAIN ANALYZE VERBOSE SELECT ... ORDER BY hot DESC`?

**Comment by lwq057** [comment] 2022-11-23 21:26
```
EXPLAIN ANALYZE VERBOSE
SELECT "ID" FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('music',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition
ORDER BY hot DESC;
```

```
Sort  (cost=4316.40..4319.07 rows=1068 width=8) (actual time=3485.679..3485.689 rows=164 loops=1)
  Output: "ID", hot
  Sort Key: data.hot DESC
  Sort Method: quicksort  Memory: 32kB
  ->  Index Scan using pgroonga_data_index2 on public.data  (cost=0.00..4262.68 rows=1068 width=8) (actual time=887.627..3483.354 rows=164 loops=1)
        Output: "ID", hot
        Index Cond: (ARRAY[(data.title)::text, data.content, (data.tag)::text, (data.author)::text] &@ '(music,"{4,1,2,3}",pgroonga_data_index2)'::pgroonga_full_text_search_condition)
Planning Time: 315.268 ms
Execution Time: 3521.476 ms
```

It's a little faster than before, but it's still not as fast as using `pgroonga_command`

And the total number of results cannot be obtained at the same time

**Comment by kou** [comment] 2022-11-23 21:36
Could you show the outputs of the following SQLs?

```sql
EXPLAIN ANALYZE VERBOSE
SELECT COUNT(*) FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('music',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition;

VACUUM VERBOSE "data";

EXPLAIN ANALYZE VERBOSE
SELECT COUNT(*) FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('music',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition;

EXPLAIN ANALYZE VERBOSE
SELECT "ID" FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('music',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition
ORDER BY hot DESC;
```

**Comment by lwq057** [comment] 2022-11-23 21:42
```
Aggregate  (cost=4265.35..4265.36 rows=1 width=8) (actual time=543.899..543.900 rows=1 loops=1)
  Output: count(*)
  ->  Index Scan using pgroonga_data_index2 on public.data  (cost=0.00..4262.68 rows=1068 width=0) (actual time=498.469..543.868 rows=164 loops=1)
        Output: "ID", title, content, tag, author, cover, "time", state, comment, hot, "like", dislike, ip, note
        Index Cond: (ARRAY[(data.title)::text, data.content, (data.tag)::text, (data.author)::text] &@ '(music,"{4,1,2,3}",pgroonga_data_index2)'::pgroonga_full_text_search_condition)
Planning Time: 224.688 ms
Execution Time: 545.344 ms
```

```
Aggregate  (cost=4281.40..4281.41 rows=1 width=8) (actual time=2.369..2.370 rows=1 loops=1)
  Output: count(*)
  ->  Index Scan using pgroonga_data_index2 on public.data  (cost=0.00..4278.72 rows=1072 width=0) (actual time=2.134..2.347 rows=164 loops=1)
        Output: "ID", title, content, tag, author, cover, "time", state, comment, hot, "like", dislike, ip, note
        Index Cond: (ARRAY[(data.title)::text, data.content, (data.tag)::text, (data.author)::text] &@ '(music,"{4,1,2,3}",pgroonga_data_index2)'::pgroonga_full_text_search_condition)
Planning Time: 1.851 ms
Execution Time: 3.163 ms
```

```
Sort  (cost=4332.67..4335.35 rows=1072 width=8) (actual time=2.416..2.424 rows=164 loops=1)
  Output: "ID", hot
  Sort Key: data.hot DESC
  Sort Method: quicksort  Memory: 32kB
  ->  Index Scan using pgroonga_data_index2 on public.data  (cost=0.00..4278.72 rows=1072 width=8) (actual time=2.155..2.378 rows=164 loops=1)
        Output: "ID", hot
        Index Cond: (ARRAY[(data.title)::text, data.content, (data.tag)::text, (data.author)::text] &@ '(music,"{4,1,2,3}",pgroonga_data_index2)'::pgroonga_full_text_search_condition)
Planning Time: 0.375 ms
Execution Time: 3.147 ms
```

**Comment by kou** [comment] 2022-11-23 21:45
It seems that you can get the total number of results and sorted K results quickly without `pgroonga_command()`.

**Comment by lwq057** [comment] 2022-11-23 21:56
I tried some other keywords, `pgroonga_command` will generally be faster

occasionally `SELECT... ORDER BY hot DESC` will be about the same speed, and it will be more slow if you need to obtain the result statistics

**Comment by lwq057** [comment] 2022-11-23 22:00
```
EXPLAIN ANALYZE VERBOSE
SELECT "ID" FROM "data"
WHERE ARRAY[title::text, content, tag::text, author::text] &@~
      ('table',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition
ORDER BY "hot" DESC
LIMIT 20;
```

```
Limit  (cost=4307.25..4307.30 rows=20 width=8) (actual time=18703.621..18703.625 rows=20 loops=1)
  Output: "ID", hot
  ->  Sort  (cost=4307.25..4309.93 rows=1072 width=8) (actual time=18703.619..18703.621 rows=20 loops=1)
        Output: "ID", hot
        Sort Key: data.hot DESC
        Sort Method: top-N heapsort  Memory: 26kB
        ->  Index Scan using pgroonga_data_index2 on public.data  (cost=0.00..4278.72 rows=1072 width=8) (actual time=125.772..18663.019 rows=59304 loops=1)
              Output: "ID", hot
              Index Cond: (ARRAY[(data.title)::text, data.content, (data.tag)::text, (data.author)::text] &@~ '(table,"{4,1,2,3}",pgroonga_data_index2)'::pgroonga_full_text_search_condition)
Planning Time: 0.165 ms
Execution Time: 18704.954 ms
```

**Comment by kou** [comment] 2022-11-23 23:46
Could you try separating `hot`?

```sql
CREATE TABLE public.data (
    "ID" integer NOT NULL PRIMARY KEY,
    title character varying(180) NOT NULL,
    content text NOT NULL,
    tag character varying(150) NOT NULL,
    author character varying(50) DEFAULT ''::character varying,
    cover text,
    "time" timestamp(0) without time zone,
    state smallint DEFAULT 0,
    comment integer DEFAULT 0,
    "like" integer DEFAULT 0,
    dislike integer DEFAULT 0,
    ip character varying(50),
    note text
);

CREATE INDEX pgroonga_data_index2
  ON public.data
 USING pgroonga ((ARRAY[title::text, content, tag::text, author::text]));


CREATE TABLE public.data_hot (
    data_id integer NOT NULL,
    hot integer NOT NULL DEFAULT 1
);

CREATE INDEX data_hot_index ON public.data_hot (data_id);

EXPLAIN ANALYZE VERBOSE
SELECT "ID"
FROM "data"
JOIN data_hot ON "data"."ID" = data_hot.data_id
WHERE ARRAY[title::text, content, tag::text, author::text] &@
      ('table',
       ARRAY[4,1,2,3],
       'pgroonga_data_index2')::pgroonga_full_text_search_condition
ORDER BY hot DESC
LIMIT 20;
```

**Comment by lwq057** [comment] 2022-11-26 18:08
@kou  thank you

I modified the query scheme. When sorting, I use the scheme you gave me. When there is no sorting, I use the previous scheme.

Although some query performance is sacrificed, the program is relatively stable.

This should be the best solution at present.

I hope pgroonga is getting better and better.

 thank you @kou

**Comment by kou** [comment] 2022-11-27 19:25
That's good to know. Then, I close this.

> I hope pgroonga is getting better and better.

FYI: You can become a financial contributor for PGroonga by Open Collective: https://opencollective.com/pgroonga

**Closed by kou** 2022-11-27 19:25 UTC
